### ISSUE TITLE
how to get text roi?

### ISSUE THREAD

**Issue by BackT0TheFuture** [gombru/TextFCN#1]
Hi,
 TextFCN is great, how to get text ROI?
thanks!

**Comment by gombru** [comment]
Hi,

Transforming pixel level detections to ROIs is not a trivial task. TextFCN is very good detecting text with hight recall, but the detections are variant in intensity and shape (for small texts it detects text blocks toguether, for bigger texts it detects words separately, etc).
In controled scenarios where the kind of text to be detected is defined, image processing and heuristics can be applied to the heatmaps to get the ROIs. However, despite we have worked on it, we haven't came out with a generic method to go from TextFCN to ROIs. Good luck with that!

**Comment by BackT0TheFuture** [comment]
got it ! thanks!
