### ISSUE TITLE
How to install and run it？

### ISSUE THREAD

**Issue by xrf116** [gombru/TextFCN#2]

**Comment by gombru** [comment]
First you need to install Caffe https://github.com/BVLC/caffe

Then, to compute heatmaps given input images, use **compute_heatmaps.py**. You have to:
- Download the [model](https://drive.google.com/file/d/0B-DM8FPBNpG6QVRLSFBNQ1dLalU/view?usp=sharing) and save it in _voc-fcn8s-atonce_ folder.
- Replace _'../../data/coco-text/val-withoutIllegible.txt'_ with the path of the txt containing your image filenames.

To train the model from scratch or fine-tune it, use **solve.py** changing the file paths.

**Comment by xrf116** [comment]
thanks
