### ISSUE TITLE
The result problem.

### ISSUE THREAD

**Issue by yeLer** [gombru/TextFCN#3]
Hello，I have used this project to do some experiments ，but I get the result is rough compare with others.
Could you give me some suggestions?Thank you very much!
The pictures are the original picture, the expected effect picture, my effect picture.
![image](https://user-images.githubusercontent.com/16631986/45753884-ae250c00-bc4c-11e8-9f43-91d4018ecfdb.png)

![image](https://user-images.githubusercontent.com/16631986/45753908-bda45500-bc4c-11e8-9dc3-1c18b856b194.png)
![image](https://user-images.githubusercontent.com/16631986/45753925-cf85f800-bc4c-11e8-9972-7a6e0e9de597.png)

**Comment by gombru** [comment]
Hello,

What is the size of the image you are inputing to TextFCN?

**Comment by yeLer** [comment]
The size of the image is 240*240.  I used the image from TotalText DataSet,which is different from training dataset.

**Comment by gombru** [comment]
Consider resizing the image to a bigger size, such as 512x512, to better fit the receptive field of the FCN.  This is the heatmap I get with that size:

![heatmap-color](https://user-images.githubusercontent.com/14967889/46011623-ba82ec00-c0c6-11e8-878b-c5bc0daf356f.jpg)

Note that the FCN is very good detecting all text instances in difficult scenarios, but is not very precise  splitting words or close text areas.
